# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [60]:
import numpy as np
from numpy import random

#### Create an array of 10 zeros 

In [2]:
l1=[0,0,0,0,0,0,0,0,0,0]
arr=np.array(l1)

In [3]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [5]:
l2=[1,1,1,1,1,1,1,1,1,1]
arr2=np.array(l2)

In [6]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [7]:
l3=[5,5,5,5,5,5,5,5,5,5]
arr3=np.array(l3)

In [8]:
arr3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [14]:
arr4 = np.arange(10,50)

In [16]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [45]:
arr5 = np.arange(10,50)

In [47]:
arr5%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [49]:
arr6=np.array(([0,1,2],[3,4,5],[6,7,8]))

In [50]:
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [51]:
arr7=np.identity(3)

In [52]:
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [66]:
arr8 = random.rand()
arr8

0.4145019043071707

In [67]:
arr8

0.4145019043071707

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [73]:
arr9 = random.normal(size=(25))

In [74]:
arr9

array([-0.08307023,  0.55992124,  1.4044201 , -0.92033079, -0.31063911,
       -0.14080398,  0.80687148,  0.25596847,  0.09637392, -0.56276752,
        1.04235524,  0.0873652 , -0.05320129, -0.0632174 , -0.19549628,
       -0.84048114, -1.09829885, -0.04601089,  2.32967817,  0.11643717,
        0.61126203, -1.16500798, -0.0679825 , -2.45491861,  0.49113151])

#### Create the following matrix:

In [86]:
mat = np.arange(0.01,1.0).reshape(5,5)
mat

ValueError: cannot reshape array of size 1 into shape (5,5)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [78]:
arr10=np.linspace(0, 1, 20)

In [79]:
arr10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [88]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
mat1=mat[2:5 ,1: 5 ]
mat1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [121]:
mat2=mat[3][4]
mat2

20

20

In [129]:
mat1=mat[0:3 ,1 ]
mat1

array([ 2,  7, 12])

array([[ 2],
       [ 7],
       [12]])

In [133]:
mat1=mat[4 ,0: 5 ]
mat1

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [136]:
mat1=mat[3:5 ,0: 5 ]
mat1

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [137]:
mat.sum()

325

325

#### Get the standard deviation of the values in mat

In [138]:
mat.std()

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [142]:
mat5=mat[: , 0:5]
mat5.sum(axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!