### problem1

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [29]:
df=pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [31]:
sex_dict={'Male':1,'Female':0}
df['Gender']=df['Gender'].map(sex_dict)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [37]:
x=df[['Gender','Age','EstimatedSalary']]
y=df['Purchased']
x

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [39]:
y_train.value_counts()

0    203
1    117
Name: Purchased, dtype: int64

In [40]:
from imblearn.over_sampling import SMOTE
sampler=SMOTE()
x_train,y_train=sampler.fit_resample(x_train,y_train)
y_train.value_counts()

0    203
1    203
Name: Purchased, dtype: int64

In [41]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report


In [64]:
models={
    'LR':LogisticRegression(),
    'KNN':KNeighborsClassifier(),
    'DT':DecisionTreeClassifier(),
    'SVC':SVC(),
    'NB':GaussianNB(),
    'XGC':XGBClassifier(),
    'RF':RandomForestClassifier()
    
}

In [47]:
for name,model in  models.items():
    print(f'using {name}: ')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Training Accuracy :{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
    print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print(f'Recall: {recall_score(y_test,y_pred)}')
    print(f'precision: {precision_score(y_test,y_pred)}')
    print(f'F1-score: {f1_score(y_test,y_pred)}')
    print(f'Fbeta-score: {fbeta_score(y_test,y_pred,beta=0.5)}')
    print('-'*33)

using LR: 
Training Accuracy :0.8448275862068966
Testing Accuracy :0.8
Confusion matrix:
 [[42 12]
 [ 4 22]]
Recall: 0.8461538461538461
precision: 0.6470588235294118
F1-score: 0.7333333333333334
Fbeta-score: 0.6790123456790124
---------------------------------
using KNN: 
Training Accuracy :0.9334975369458128
Testing Accuracy :0.8875
Confusion matrix:
 [[49  5]
 [ 4 22]]
Recall: 0.8461538461538461
precision: 0.8148148148148148
F1-score: 0.830188679245283
Fbeta-score: 0.8208955223880597
---------------------------------
using DT: 
Training Accuracy :0.9975369458128078
Testing Accuracy :0.875
Confusion matrix:
 [[48  6]
 [ 4 22]]
Recall: 0.8461538461538461
precision: 0.7857142857142857
F1-score: 0.8148148148148148
Fbeta-score: 0.7971014492753622
---------------------------------
using SVC: 
Training Accuracy :0.9285714285714286
Testing Accuracy :0.9125
Confusion matrix:
 [[49  5]
 [ 2 24]]
Recall: 0.9230769230769231
precision: 0.8275862068965517
F1-score: 0.8727272727272727
Fbeta-score: 

C:\an\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:28:12] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy :0.9926108374384236
Testing Accuracy :0.8625
Confusion matrix:
 [[48  6]
 [ 5 21]]
Recall: 0.8076923076923077
precision: 0.7777777777777778
F1-score: 0.7924528301886792
Fbeta-score: 0.7835820895522388
---------------------------------
using RF: 
Training Accuracy :0.9975369458128078
Testing Accuracy :0.8625
Confusion matrix:
 [[48  6]
 [ 5 21]]
Recall: 0.8076923076923077
precision: 0.7777777777777778
F1-score: 0.7924528301886792
Fbeta-score: 0.7835820895522388
---------------------------------


In [48]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [49]:
x.columns

Index(['Gender', 'Age', 'EstimatedSalary'], dtype='object')

In [50]:
import joblib
joblib.dump(model,'model.h5')
joblib.dump(scaler,'scaler.h5')

['scaler.h5']

### Problem2

In [96]:
df=pd.read_csv('Titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [98]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [99]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [100]:
df.shape

(891, 12)

In [101]:
df.drop(['Embarked','Cabin'],axis=1,inplace=True)


In [79]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  
0      0         A/5 21171   7.2500  
1      0          PC 17599  71.2833  
2      0  STON/O2. 3101282   7.9250  
3      0            113803  53.1000  
4      0            373450   8.0500

In [102]:
df.drop(df.columns[8],axis=1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch     Fare  
0        0   7.2500  
1        0  71.2833  
2        0   7.9250  
3        0  53.1000  
4        0   8.0500  
..     ...      ...  
886      0  13.0000  
887      0  30.0000  
888      2  23.4500  
889      0  30.0000  
890      0   7.7500  

[891 rows x 9 columns]

In [103]:
sex_dict={'male':1,'female':0}
df['Sex']=df['Sex'].map(sex_dict)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  
0         A/5 21171   7.2500  
1          PC 17599  71.2833  
2  STON/O2. 3101282   7.9250  
3            113803  53.1000  
4            373450   8.0500

In [107]:
df["Age"].fillna( method ='ffill', inplace = True)

In [108]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

In [109]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  
0         A/5 21171   7.2500  
1          PC 17599  71.2833  
2  STON/O2. 3101282   7.9250  
3            113803  53.1000  
4            373450   8.0500

In [110]:
x=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare']]
y=df['Survived']
x

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare
0              1       3    1  22.0      1      0   7.2500
1              2       1    0  38.0      1      0  71.2833
2              3       3    0  26.0      0      0   7.9250
3              4       1    0  35.0      1      0  53.1000
4              5       3    1  35.0      0      0   8.0500
..           ...     ...  ...   ...    ...    ...      ...
886          887       2    1  27.0      0      0  13.0000
887          888       1    0  19.0      0      0  30.0000
888          889       3    0  19.0      1      2  23.4500
889          890       1    1  26.0      0      0  30.0000
890          891       3    1  32.0      0      0   7.7500

[891 rows x 7 columns]

In [111]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [112]:
y_train.value_counts()

0    440
1    272
Name: Survived, dtype: int64

In [113]:
from imblearn.over_sampling import SMOTE
sampler=SMOTE()
x_train,y_train=sampler.fit_resample(x_train,y_train)
y_train.value_counts()

0    440
1    440
Name: Survived, dtype: int64

In [114]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [115]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report


In [116]:
for name,model in  models.items():
    print(f'using {name}: ')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Training Accuracy :{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
    print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print(f'Recall: {recall_score(y_test,y_pred)}')
    print(f'precision: {precision_score(y_test,y_pred)}')
    print(f'F1-score: {f1_score(y_test,y_pred)}')
    print(f'Fbeta-score: {fbeta_score(y_test,y_pred,beta=0.5)}')
    print('-'*33)

using LR: 
Training Accuracy :0.8193181818181818
Testing Accuracy :0.7877094972067039
Confusion matrix:
 [[88 21]
 [17 53]]
Recall: 0.7571428571428571
precision: 0.7162162162162162
F1-score: 0.736111111111111
Fbeta-score: 0.7240437158469946
---------------------------------
using KNN: 
Training Accuracy :0.8738636363636364
Testing Accuracy :0.7653631284916201
Confusion matrix:
 [[82 27]
 [15 55]]
Recall: 0.7857142857142857
precision: 0.6707317073170732
F1-score: 0.7236842105263158
Fbeta-score: 0.6909547738693468
---------------------------------
using DT: 
Training Accuracy :1.0
Testing Accuracy :0.7597765363128491
Confusion matrix:
 [[81 28]
 [15 55]]
Recall: 0.7857142857142857
precision: 0.6626506024096386
F1-score: 0.7189542483660131
Fbeta-score: 0.6840796019900498
---------------------------------
using SVC: 
Training Accuracy :0.8556818181818182
Testing Accuracy :0.8212290502793296
Confusion matrix:
 [[94 15]
 [17 53]]
Recall: 0.7571428571428571
precision: 0.7794117647058824
F1-sc

C:\an\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[00:14:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy :1.0
Testing Accuracy :0.7877094972067039
Confusion matrix:
 [[89 20]
 [18 52]]
Recall: 0.7428571428571429
precision: 0.7222222222222222
F1-score: 0.732394366197183
Fbeta-score: 0.7262569832402235
---------------------------------
using RF: 
Training Accuracy :1.0
Testing Accuracy :0.8156424581005587
Confusion matrix:
 [[94 15]
 [18 52]]
Recall: 0.7428571428571429
precision: 0.7761194029850746
F1-score: 0.759124087591241
Fbeta-score: 0.7692307692307693
---------------------------------


In [117]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [118]:
import joblib
joblib.dump(model,'model.h6')
joblib.dump(scaler,'scaler.h6')

['scaler.h6']